Loadtest dev ops 2598
hpi-schul-cloud/load-tests pull request #8
Opened 2021-07-29 11:35 UTC by FelixBlauza

Code Redesign
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2598

Comment the Code
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2577

Lernstore implemented
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2513

2021-07-29 15:05 UTC, dimapin requested changes

2021-07-29 15:05 UTC, dimapin commented on bbbTaskSet.py
> +        bBBKey (str) : key for using BBB
No context here and not clear how they are used

2021-07-29 15:05 UTC, dimapin commented on bbbTaskSet.py
> +            urlparam = "meetingID=loadtest-" + timestamp + str(counterfirst) + "&name=loadtest-" + str(time.time()) + str(counterfirst) + "&moderatorPW=123&attendeePW=456&lockSettingsDisableMic=true"
Where does "&moderatorPW=123&attendeePW=456&lockSettingsDisableMic=true" come from?

2021-07-29 15:05 UTC, dimapin commented on constant.py
> +    matrixMessengerHost = os.environ.get("MMHOST")
Please write MATRIXMESSENGER or MATRIX_MESSENGER

2021-07-29 15:05 UTC, dimapin commented on constant.py
> +    numberRooms = 3 #int(os.environ.get("BBBNUMBERROOMS"))
Why is the parametrization via environment variable disabled?

2021-07-29 15:05 UTC, dimapin commented on constant.py
> +    urlReqWithoutUser = "niedersachsen.cloud" # Used for reqWithoutUserTaskSet as url
Why is this hardcoded?

2021-07-29 15:05 UTC, dimapin commented on docTaskSet.py
> +    #@tag('test')
please remove

2021-07-29 15:05 UTC, dimapin commented on loginout.py
> +                self.bearer_token = (response_header["set-cookie"]).split(";")[0].replace("jwt=", "")
Some explanation, what is happening here and why.

2021-07-29 15:05 UTC, dimapin commented on requestsBuilder.py
> +    for res in soup.find_all(href=True):
Svg and font files are missing here

2021-07-29 15:05 UTC, dimapin commented on requestsBuilder.py
> +def lernStore(self):
Please split this method. 'and' is a sign, that the method should be splitted.

2021-07-29 15:05 UTC, dimapin commented on requestsBuilder.py
> +                "https://api.staging.niedersachsen.hpi-schul-cloud.org/lessons?courseId=" + courseId,
Hard coded target

2021-07-29 15:05 UTC, dimapin commented on requestsBuilder.py
> +                    "https://api.staging.niedersachsen.hpi-schul-cloud.org/lessons/" + courseId_Lernstore + "/material",
Hard coded url

2021-07-29 15:05 UTC, dimapin commented on requestsBuilder.py
> +            data = "privacy_permission=anonymous&openNewTab=true&name=bettermarks&url=https://acc.bettermarks.com/Fv1.0/schulcloud/de_ni_staging/login&key=&logo_url=https://acc.bettermarks.com/app/as
The part acc.bettermarks.com should be configurable

2021-07-29 15:05 UTC, dimapin commented on requestsBuilder.py
> +    courseId = createCourse(self, courseDataBuilder(self))
Is the order right here? Can a Pupil create a course?

2021-07-29 15:05 UTC, dimapin commented on requestsBuilder.py
> +                    #name="https://matrix.niedersachsen.messenger.schule/_matrix/client/r0/rooms/" + room_id + "/send/m.room.message"
Please remove commented out code

2021-07-29 15:05 UTC, dimapin commented on requestsBuilder.py
> +def matrixMessenger(self):
Leave a comment about a status

2021-07-29 15:26 UTC, MartinNeum commented on bbbTaskSet.py
> +        bBBKey (str) : key for using BBB
Deletec because the variables are availible on the constant.py-file now

2021-07-29 15:27 UTC, MartinNeum commented on constant.py
> +    numberRooms = 3 #int(os.environ.get("BBBNUMBERROOMS"))
Enabled enviroment parametrization

2021-07-29 15:38 UTC, MartinNeum commented on constant.py
> +    urlReqWithoutUser = "niedersachsen.cloud" # Used for reqWithoutUserTaskSet as url
Removed because no longer neccessary. 'reqWithoutUser' further will use the host domain to make reqests on /version, api./version and /nuxtversion.

2021-07-29 16:20 UTC, FelixBlauza commented on loginout.py
> +                self.bearer_token = (response_header["set-cookie"]).split(";")[0].replace("jwt=", "")
Commented in the Code

2021-07-30 05:39 UTC, FelixBlauza commented on docTaskSet.py
> +    #@tag('test')
Is deleted

2021-07-30 05:44 UTC, FelixBlauza commented on bbbTaskSet.py
> +            urlparam = "meetingID=loadtest-" + timestamp + str(counterfirst) + "&name=loadtest-" + str(time.time()) + str(counterfirst) + "&moderatorPW=123&attendeePW=456&lockSettingsDisableMic=true"
Random Information, which ware needed to separate moderators and normal attendees.

2021-07-30 05:47 UTC, FelixBlauza commented on requestsBuilder.py
> +                "https://api.staging.niedersachsen.hpi-schul-cloud.org/lessons?courseId=" + courseId,
Changed to a more flexible url.

2021-07-30 05:47 UTC, FelixBlauza commented on requestsBuilder.py
> +                    "https://api.staging.niedersachsen.hpi-schul-cloud.org/lessons/" + courseId_Lernstore + "/material",
Changed to a more flexible url.

2021-07-30 05:49 UTC, FelixBlauza commented on requestsBuilder.py
> +    courseId = createCourse(self, courseDataBuilder(self))
The order is right. Pupil User will not reach this section.

2021-07-30 05:51 UTC, FelixBlauza commented on requestsBuilder.py
> +                    #name="https://matrix.niedersachsen.messenger.schule/_matrix/client/r0/rooms/" + room_id + "/send/m.room.message"
Removed

2021-07-30 05:51 UTC, FelixBlauza commented on requestsBuilder.py
> +def matrixMessenger(self):
Done

2021-08-02 07:51 UTC, MartinNeum commented on requestsBuilder.py
> +    for res in soup.find_all(href=True):
Added .svg and fonts

2021-08-02 07:52 UTC, MartinNeum approved these changes

2021-08-02 09:19 UTC, MartinNeum approved these changes

2021-08-02 11:06 UTC, dimapin approved these changes

2021-08-02 11:10 UTC, merged